In [2]:
corpus = [
    'the sun is a star',
    'the moon is a satellite',
    'the sun and moon are celestial bodies'
]

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
vectorizer=CountVectorizer()

In [5]:
vectorizer.fit(corpus)

CountVectorizer()

In [6]:
print( vectorizer.vocabulary_)


{'the': 9, 'sun': 8, 'is': 4, 'star': 7, 'moon': 5, 'satellite': 6, 'and': 0, 'are': 1, 'celestial': 3, 'bodies': 2}


In [7]:
vector = vectorizer.transform(corpus)


In [8]:
print(vector.toarray())

[[0 0 0 0 1 0 0 1 1 1]
 [0 0 0 0 1 1 1 0 0 1]
 [1 1 1 1 0 1 0 0 1 1]]


In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
tfidf = TfidfVectorizer()

In [11]:
result = tfidf.fit_transform(corpus)

In [13]:
print(tfidf.vocabulary_)

{'the': 9, 'sun': 8, 'is': 4, 'star': 7, 'moon': 5, 'satellite': 6, 'and': 0, 'are': 1, 'celestial': 3, 'bodies': 2}


In [14]:
print(result)

  (0, 9)	0.3731188059313277
  (0, 8)	0.4804583972923858
  (0, 4)	0.4804583972923858
  (0, 7)	0.6317450542765208
  (1, 9)	0.3731188059313277
  (1, 4)	0.4804583972923858
  (1, 5)	0.4804583972923858
  (1, 6)	0.6317450542765208
  (2, 9)	0.2517108425440014
  (2, 8)	0.3241235393856436
  (2, 5)	0.3241235393856436
  (2, 0)	0.42618350336974425
  (2, 1)	0.42618350336974425
  (2, 3)	0.42618350336974425
  (2, 2)	0.42618350336974425


In [15]:
import pandas as pd


In [61]:
import pandas as pd

# Try Latin-1
data1 = pd.read_csv('spam.csv', encoding='latin-1')


In [62]:
data1.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [64]:
# Strip leading/trailing whitespace (including tabs) from every column name
data1.columns = data1.columns.str.strip()


In [65]:
data1.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [67]:
# Drop every column whose name begins with "Unnamed"
data1.drop(
    columns=data1.columns[data1.columns.str.startswith('Unnamed')],
    inplace=True
)


In [21]:
data.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [70]:
data1['ham or spam']=data1['v1']

In [72]:
data1.head()

v1                                                 v2 ham or spam
0   ham  Go until jurong point, crazy.. Available only ...         ham
1   ham                      Ok lar... Joking wif u oni...         ham
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        spam
3   ham  U dun say so early hor... U c already then say...         ham
4   ham  Nah I don't think he goes to usf, he lives aro...         ham

In [73]:
data1.drop(['v1','v2'],axis=1,inplace=True)

In [25]:
data.head()

text
0  Go until jurong point, crazy.. Available only ...
1                      Ok lar... Joking wif u oni...
2  Free entry in 2 a wkly comp to win FA Cup fina...
3  U dun say so early hor... U c already then say...
4  Nah I don't think he goes to usf, he lives aro...

In [28]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mahes\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [29]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [30]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mahes\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [31]:
stop_words = set(stopwords.words('english'))

In [32]:
def normalize_and_tokenize(text):
    
    text = str(text).lower().strip()
    
    tokens = word_tokenize(text)
    
    tokens = [tok for tok in tokens if tok.isalpha() and tok not in stop_words]
    return tokens

In [33]:
data['tokens'] = data['text'].apply(normalize_and_tokenize)


In [34]:
data.head()

text  \
0  Go until jurong point, crazy.. Available only ...   
1                      Ok lar... Joking wif u oni...   
2  Free entry in 2 a wkly comp to win FA Cup fina...   
3  U dun say so early hor... U c already then say...   
4  Nah I don't think he goes to usf, he lives aro...   

                                              tokens  
0  [go, jurong, point, crazy, available, bugis, n...  
1                     [ok, lar, joking, wif, u, oni]  
2  [free, entry, wkly, comp, win, fa, cup, final,...  
3      [u, dun, say, early, hor, u, c, already, say]  
4     [nah, think, goes, usf, lives, around, though]

In [35]:
pip install genism

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement genism (from versions: none)
ERROR: No matching distribution found for genism


In [36]:
from gensim.models import Word2Vec

In [37]:
import gensim.downloader as api

In [42]:
import numpy as np
from gensim.models import KeyedVectors

In [44]:
model = api.load('word2vec-google-news-300') 

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [48]:
vector_size = model.vector_size

In [57]:
def avg_word2vec(tokens, model, vector_size):
    valid = [tok for tok in tokens if tok in model]
    if not valid:
        return np.zeros(vector_size, dtype=float)
    return np.mean([model[t] for t in valid], axis=0)

In [58]:
data['w2v_avg'] = data['tokens'].apply(lambda token_list: 
    avg_word2vec(token_list, model, model.vector_size)
)

In [59]:
data.head()

text  \
0  Go until jurong point, crazy.. Available only ...   
1                      Ok lar... Joking wif u oni...   
2  Free entry in 2 a wkly comp to win FA Cup fina...   
3  U dun say so early hor... U c already then say...   
4  Nah I don't think he goes to usf, he lives aro...   

                                              tokens  \
0  [go, jurong, point, crazy, available, bugis, n...   
1                     [ok, lar, joking, wif, u, oni]   
2  [free, entry, wkly, comp, win, fa, cup, final,...   
3      [u, dun, say, early, hor, u, c, already, say]   
4     [nah, think, goes, usf, lives, around, though]   

                                             w2v_avg  
0  [-0.019805908, 0.05167062, 0.02709961, 0.21868...  
1  [-0.06323496, 0.0803833, 0.060943604, 0.102498...  
2  [-0.03242302, -0.0050720214, -0.06273012, 0.11...  
3  [-0.06568061, 0.0262146, 0.1081543, 0.0869751,...  
4  [0.032470703, 0.037462506, 0.047345843, 0.1572...

In [74]:
data1['ham or spam'] = data1['ham or spam'].map({'spam': 1, 'ham': 0})

In [75]:
data2=data.drop(['text','tokens'],axis=1)

In [77]:
ultimatedata=pd.concat([data1,data2],axis=1)

In [79]:
ultimatedata.tail()

ham or spam                                            w2v_avg
5567            1  [0.013605291, 0.04226962, 0.020129116, 0.04342...
5568            0  [0.021606445, 0.090625, 0.109191895, 0.0634216...
5569            0  [0.044270832, 0.15771484, 0.0152994795, 0.0895...
5570            0  [0.09965633, 0.027118389, -0.015331562, 0.0777...
5571            0  [0.111979164, 0.0679423, 0.087239586, 0.075764...

In [80]:
from sklearn.model_selection import train_test_split

In [91]:
x = np.array(ultimatedata['w2v_avg'].tolist(), dtype=float)

In [92]:
X

array([[-0.01980591,  0.05167062,  0.02709961, ..., -0.07992554,
        -0.05235944,  0.03033665],
       [-0.06323496,  0.0803833 ,  0.0609436 , ..., -0.11419169,
        -0.07287598,  0.10921224],
       [-0.03242302, -0.00507202, -0.06273012, ..., -0.10424729,
        -0.11720543,  0.03997059],
       ...,
       [ 0.04427083,  0.15771484,  0.01529948, ..., -0.03629557,
        -0.02042643,  0.00728353],
       [ 0.09965633,  0.02711839, -0.01533156, ..., -0.06056565,
        -0.00980377, -0.04541016],
       [ 0.11197916,  0.0679423 ,  0.08723959, ..., -0.05094401,
        -0.13898213,  0.01904297]])

In [93]:
y=ultimatedata['ham or spam'].values

In [94]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 2)

In [95]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [96]:
model1 = LogisticRegression()

In [97]:
model1.fit(x_train,y_train)

LogisticRegression()

In [103]:
y_pred_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [98]:
y_pred_test = model1.predict(x_test)


In [99]:
test_acc = accuracy_score(y_test, y_pred_test)

In [100]:
test_acc

0.9443946188340807

In [101]:
print(confusion_matrix(y_test, y_pred_test))

[[942  15]
 [ 47 111]]


In [114]:
def predict_message(model,w2vmodel,sentence):
    words = sentence.lower().split()
    
    vector = avg_word2vec(words,w2vmodel,w2vmodel.vector_size)
    x=vector.reshape(1,-1)
    if model.predict(x)==0:
        print('ham')
    else:
        print('spam')

In [115]:
sentence='free cash'
predict_message(model1,model,sentence)

spam


In [ ]:
# 2

In [116]:
mydata=pd.read_csv('Tweets.csv')

In [120]:
mydata.drop(['tweet_id','negativereason','airline_sentiment_confidence','negativereason_confidence','airline','airline_sentiment_gold','name','negativereason_gold','retweet_count','tweet_coord','tweet_created',	'tweet_location',	'user_timezone'],axis=1,inplace=True)

In [121]:
mydata.head()

airline_sentiment                                               text
0           neutral                @VirginAmerica What @dhepburn said.
1          positive  @VirginAmerica plus you've added commercials t...
2           neutral  @VirginAmerica I didn't today... Must mean I n...
3          negative  @VirginAmerica it's really aggressive to blast...
4          negative  @VirginAmerica and it's a really big bad thing...

In [122]:
mydata.tail()

airline_sentiment                                               text
14635          positive  @AmericanAir thank you we got on a different f...
14636          negative  @AmericanAir leaving over 20 minutes Late Flig...
14637           neutral  @AmericanAir Please bring American Airlines to...
14638          negative  @AmericanAir you have my money, you change my ...
14639           neutral  @AmericanAir we have 8 ppl so we need 2 know h...

In [126]:
import re
import pandas as pd
import nltk
import emoji
import contractions
from nltk.stem import WordNetLemmatizer

In [125]:
!pip install emoji contractions


   ---------------------------------------- 0.0/590.6 kB ? eta -:--:--
   ----------------- ---------------------- 262.1/590.6 kB ? eta -:--:--
   ---------------------------------------- 590.6/590.6 kB 1.5 MB/s eta 0:00:00


In [127]:
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mahes\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mahes\AppData\Roaming\nltk_data...


True

In [128]:
lemmatizer = WordNetLemmatizer()

In [129]:
def clean_text(s: str) -> str:
    # a) to string, lowercase and strip
    s = str(s).lower().strip()

    # b) expand common contractions
    s = contractions.fix(s)

    # c) remove URLs
    s = re.sub(r'https?://\S+|www\.\S+', '', s)

    # d) remove @mentions and #hashtags
    s = re.sub(r'@\w+|#\w+', '', s)

    # e) remove punctuation (keep whitespace and word‐chars)
    s = re.sub(r'[^\w\s]', ' ', s)

    # f) remove emojis and other symbols
    s = emoji.replace_emoji(s, replace='')  # requires `emoji` package

    # g) tokenize on whitespace
    tokens = s.split()

    # h) lemmatize each token
    tokens = [lemmatizer.lemmatize(tok) for tok in tokens]

    # i) re‐join into a cleaned string (or return tokens list if you prefer)
    return ' '.join(tokens)

In [130]:
mydata['cleaned text'] = mydata['text'].apply(clean_text)

In [132]:
mydata.drop(['text'],axis=1,inplace=True)

In [133]:
mydata.head()

airline_sentiment                                       cleaned text
0           neutral                                          what said
1          positive  plus you have added commercial to the experien...
2           neutral  i did not today must mean i need to take anoth...
3          negative  it is really aggressive to blast obnoxious ent...
4          negative          and it is a really big bad thing about it

In [134]:
def avg_word2vec1(sentence, model):
    words = sentence.lower().split()
    valid_vectors = [model[word] for word in words if word in model]
    
    if not valid_vectors:
        return np.zeros(model.vector_size)
    
    return np.mean(valid_vectors, axis=0)

In [136]:
mydata['w2v_avg'] = mydata['cleaned text'].apply(lambda token_list: 
    avg_word2vec1(token_list, model)
)

In [138]:
mydata.drop(['cleaned text'],axis=1,inplace=True)

In [139]:
label2id = {
    "negative": 0,
    "neutral":  1,
    "positive": 2,
}

In [141]:
mydata['airline_sentiment'] = mydata['airline_sentiment'].map(label2id)

In [143]:
mydata.head()

airline_sentiment                                            w2v_avg
0                  1  [0.0652771, -0.025177002, 0.15722656, -0.00170...
1                  2  [0.025238037, -0.0074768066, -0.0210495, 0.082...
2                  1  [-0.01674028, 0.032792524, 0.059326172, 0.0763...
3                  0  [0.018322945, 0.063874125, 0.012535095, 0.0904...
4                  0  [0.102321625, 0.011981487, 0.059326172, 0.0765...

In [144]:
X = np.array(mydata['w2v_avg'].tolist(), dtype=float)

In [145]:
Y=mydata['airline_sentiment'].values

In [142]:
model2=LogisticRegression()

In [146]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state = 2)

In [147]:
model2.fit(X_train,Y_train)

LogisticRegression()

In [148]:
y_predtest=model2.predict(X_test)

In [149]:
y_predtest

array([2, 0, 1, ..., 0, 0, 0], dtype=int64)

In [150]:
test_acc1 = accuracy_score(Y_test, y_predtest)

In [151]:
test_acc1 

0.7687841530054644

In [161]:
def predict_tweet(model,w2vmodel,sentence):
    words=clean_text(sentence)
    
    
    vector = avg_word2vec1(words,w2vmodel)
    x=vector.reshape(1,-1)
    if model.predict(x)==0:
        print('negative')
    elif model.predict(x)==1:
        print('neutral')
    elif model.predict(x)==2:
        print('positive')

In [162]:
sentence='horrible experience'
predict_tweet(model2,model,sentence)

negative
