In [3]:
print('HELLO WORLD')


HELLO WORLD


In [ ]:
# 1

In [4]:
import numpy as np

In [5]:
df=np.random.randint(2,50,size=(5,4))

In [6]:
print(df)

[[33  2 26  7]
 [47  3 46 40]
 [13  9 39 14]
 [13 41 38 28]
 [47 26 19  2]]


In [7]:
r,c=df.shape

In [8]:
i=0
diagonal_elements=[]
for j in range(3,-1,-1):
    diagonal_elements.append(df[i][j])
    i+=1
    
    

In [9]:
diagonal_elements

[7, 46, 9, 13]

In [10]:
for i in range(0,5):
    
    ab=df[i:5][:1]
    print(np.max( ab))

33
47
39
41
47


In [11]:
overall_mean=df.mean()

In [12]:
matrix=df

In [13]:
new_element=[]

for i in range(len(matrix)):  # Loop through rows
    for j in range(len(matrix[i])):  # Loop through columns in each row
        if matrix[i][j] <= overall_mean:
            new_element.append(matrix[i][j])
            
        else:
            pass

In [14]:
new_element

[2, 7, 3, 13, 9, 14, 13, 19, 2]

In [15]:
def spiral(arr):
    element=[]
    row,coloumn=arr.shape
    top,down=0,row-1
    left,right=0,coloumn-1
              
          
    for i in range(left,right+1):
                element.append(arr[top][i])
    top+=1       
        
    for j in range(top,down+1):
               element.append(arr[j][right])
    right-=1        
    if top<=down:
           for k in range(right,left-1,-1):
               element.append(arr[down][k])
    down-=1       
    if left<=right:
           for l in range(down,top-1,-1):
               element.append(arr[l][left])
              
    return element

In [16]:
spiral(df)

[33, 2, 26, 7, 40, 14, 28, 2, 19, 26, 47, 13, 13, 47]

In [17]:
df

array([[33,  2, 26,  7],
       [47,  3, 46, 40],
       [13,  9, 39, 14],
       [13, 41, 38, 28],
       [47, 26, 19,  2]])

In [ ]:
# 2

In [18]:
df1=np.random.uniform(1,10,size=20)

In [19]:
dfnew=df1.round(2)

In [20]:
dfnew

array([7.5 , 1.65, 9.36, 2.01, 7.14, 5.15, 3.88, 5.1 , 7.17, 7.52, 1.33,
       7.31, 5.56, 6.  , 8.9 , 7.29, 5.62, 4.65, 2.36, 6.1 ])

In [21]:
dfnew.max()

9.36

In [22]:
dfnew.min()

1.33

In [23]:
np.median(dfnew)

5.8100000000000005

In [24]:
for i in range(len(dfnew)):
    if dfnew[i]<5:
        dfnew[i]=dfnew[i]*dfnew[i]
    else:
        pass

In [25]:
dfnew.argmin()

10

In [26]:
dfnew

array([ 7.5   ,  2.7225,  9.36  ,  4.0401,  7.14  ,  5.15  , 15.0544,
        5.1   ,  7.17  ,  7.52  ,  1.7689,  7.31  ,  5.56  ,  6.    ,
        8.9   ,  7.29  ,  5.62  , 21.6225,  5.5696,  6.1   ])

In [27]:
def sort_array(arr):
    sorted_array=[]
    while len(arr)>0:
        p=arr.argmin()
        sorted_array.append(arr[p])
        arr=np.delete(arr,p)
        if len(arr)>0:
            
            
            q=arr.argmax()
            sorted_array.append(arr[q])
            arr=np.delete(arr,q)
    return sorted_array    
        
        

In [28]:
sort_array(dfnew)

[1.7689000000000001,
 21.622500000000002,
 2.7224999999999997,
 15.0544,
 4.040099999999999,
 9.36,
 5.1,
 8.9,
 5.15,
 7.52,
 5.56,
 7.5,
 5.569599999999999,
 7.31,
 5.62,
 7.29,
 6.0,
 7.17,
 6.1,
 7.14]

In [ ]:
#3

In [33]:
dataframe=pd.DataFrame(np.random.randint(51,100,size=(10,3)))

In [34]:
import pandas as pd

In [35]:
dataframe.head()

0   1   2
0  74  96  85
1  55  89  71
2  70  88  56
3  81  77  99
4  63  92  68

In [36]:
dataframe=dataframe.rename(columns={0:'Name',1:'Subject',2:'Score'})

In [37]:
dataframe

Name  Subject  Score
0    74       96     85
1    55       89     71
2    70       88     56
3    81       77     99
4    63       92     68
5    75       56     53
6    78       80     85
7    61       83     78
8    73       81     59
9    89       87     97

In [130]:
dataframe['grade']=''
for i in range(len(dataframe)):
     if dataframe['Score'][i]>=90:
         dataframe['grade'][i]='A'
     elif dataframe['Score'][i]>=80:
         dataframe['grade'][i]='B'
     elif dataframe['Score'][i]>=70:
         dataframe['grade'][i]='C'
    
     elif dataframe['Score'][i]>=60:
         
         dataframe['grade'][i]='D'
     
         
     elif dataframe['Score'][i]<=59:
         dataframe['grade'][i]='F'

C:\Users\mahes\AppData\Local\Temp\ipykernel_62328\498216382.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['grade'][i]='A'
C:\Users\mahes\AppData\Local\Temp\ipykernel_62328\498216382.py:4: SettingWithCopyWarning: 
A value is t

In [39]:
dataframe['Score'][0]

85

In [40]:
len(dataframe)

10

In [41]:
dataframe

Name  Subject  Score grade
0    74       96     85     B
1    55       89     71     C
2    70       88     56     F
3    81       77     99     A
4    63       92     68     D
5    75       56     53     F
6    78       80     85     B
7    61       83     78     C
8    73       81     59     F
9    89       87     97     A

In [42]:
dataframe=dataframe.sort_values(by='Score', ascending=False).reset_index()

In [43]:
dataframe

index  Name  Subject  Score grade
0      3    81       77     99     A
1      9    89       87     97     A
2      0    74       96     85     B
3      6    78       80     85     B
4      7    61       83     78     C
5      1    55       89     71     C
6      4    63       92     68     D
7      8    73       81     59     F
8      2    70       88     56     F
9      5    75       56     53     F

In [46]:
def filterpass(dataframe):
    
    
    
     filterdataframe=dataframe[(dataframe['grade']=='A') |  (dataframe['grade']=='B')]
     return filterdataframe

In [47]:
filterpass(dataframe)

index  Name  Subject  Score grade
0      3    81       77     99     A
1      9    89       87     97     A
2      0    74       96     85     B
3      6    78       80     85     B

#YOU CAN ACTUALLY CALCULATE THE MEAN OF THE SUCJECT BY FILTERING THE REQUIRED SUBJECT AND GET ITS MEAN BY MEAN FUNCTION I COULDN'T DO HERE DUE TO DIFFERENT DATA SET


In [ ]:
# 4

In [48]:
reviews=pd.read_csv('REVIEWS.csv')

In [49]:
reviews.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5450 entries, 0 to 5449
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      5450 non-null   int64 
 1   REVIEW  5450 non-null   object
 2   RATING  5450 non-null   object
 3   AUTHOR  5450 non-null   object
 4   TITLE   5450 non-null   object
dtypes: int64(1), object(4)
memory usage: 213.0+ KB


In [50]:
POSITIVE=reviews[(reviews['RATING']=='10')|(reviews['RATING']=='9')|(reviews['RATING']=='8')].reset_index()

In [51]:
positive=POSITIVE.head(50)

In [52]:
NEGATIVE=reviews[(reviews['RATING']=='3')|(reviews['RATING']=='1')|(reviews['RATING']=='2')].reset_index()

In [53]:
negative=NEGATIVE.head(50)

In [54]:
ultimate=pd.concat([positive,negative],axis=0,ignore_index=True,join='outer')

In [55]:
ultimate.tail()

index   ID                                             REVIEW RATING  \
95    135  136  A truly awful outing for Snyder. Thin dumb plo...      2   
96    136  137  Besides being a beat for beat, and markedly in...      1   
97    137  138  If the blood is so valuable - why not just sen...      3   
98    138  139  I don't bother with trailers and previews so t...      3   
99    139  140  I rated it 2/10 just because of the stunning v...      2   

             AUTHOR                                              TITLE  
95  leewelton-81877   Needs a quick headshot to put it out of its m...  
96         aerie124   This movie insults your intelligence - this m...  
97        amw-30184           2.5 hours of plot holes and questions.\n  
98       pizzadudes                                    Disappointing\n  
99  nadiaafreendiba                        The worst from Snyder yet\n

In [56]:
ultimate=ultimate.drop(['index','ID','AUTHOR','TITLE'],axis=1)

In [57]:
ultimate

REVIEW RATING
0   I cannot believe anyone could give this film l...      8
1   Much better than the ratings suggest. Its on p...      9
2   Okay so first I am a big fan of shark movies. ...      8
3   Another shark tale.. But much better than most...      8
4   All those that gave this less than a 5 are idi...     10
..                                                ...    ...
95  A truly awful outing for Snyder. Thin dumb plo...      2
96  Besides being a beat for beat, and markedly in...      1
97  If the blood is so valuable - why not just sen...      3
98  I don't bother with trailers and previews so t...      3
99  I rated it 2/10 just because of the stunning v...      2

[100 rows x 2 columns]

In [58]:
ultimate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   REVIEW  100 non-null    object
 1   RATING  100 non-null    object
dtypes: object(2)
memory usage: 1.7+ KB


In [59]:
ultimate.head()

REVIEW RATING
0  I cannot believe anyone could give this film l...      8
1  Much better than the ratings suggest. Its on p...      9
2  Okay so first I am a big fan of shark movies. ...      8
3  Another shark tale.. But much better than most...      8
4  All those that gave this less than a 5 are idi...     10

In [60]:
ultimate['RATING'] = pd.to_numeric(ultimate['RATING'], errors='coerce')

In [129]:
ultimate['Sentiment']=''
for i in range(len(ultimate)):
    if ultimate['RATING'][i]>=5:
        ultimate['Sentiment'][i]='positive'
    elif ultimate['RATING'][i]<5:
        ultimate['Sentiment'][i]='negative'
        
    

KeyError: 'RATING'

In [62]:
ultimate=ultimate.drop(['RATING'],axis=1)

In [63]:
ultimate.head()
    

REVIEW Sentiment
0  I cannot believe anyone could give this film l...  positive
1  Much better than the ratings suggest. Its on p...  positive
2  Okay so first I am a big fan of shark movies. ...  positive
3  Another shark tale.. But much better than most...  positive
4  All those that gave this less than a 5 are idi...  positive

In [64]:
ultimate.loc[0]

REVIEW       I cannot believe anyone could give this film l...
Sentiment                                             positive
Name: 0, dtype: object

In [68]:
i = 0
while i <= 48:
    
    row_a = ultimate.iloc[i].values.copy()
    row_b = ultimate.iloc[50 + i].values.copy()
    
    
    ultimate.iloc[i]          = row_b
    ultimate.iloc[50 + i]     = row_a
    
    
    i += 2

In [69]:
ultimate.head()

REVIEW Sentiment
0  At least well 2/3's of the movie, its grumpy m...  negative
1  Much better than the ratings suggest. Its on p...  positive
2  When u come to watch a typical shark movie , y...  negative
3  Another shark tale.. But much better than most...  positive
4  I am very impressed how a mouth to mouth under...  negative

In [70]:
from sklearn.feature_extraction.text import CountVectorizer

In [76]:
from sklearn.model_selection import train_test_split


In [77]:
vectorizer = CountVectorizer(max_features=500, stop_words="english")

In [78]:
X = vectorizer.fit_transform(ultimate["REVIEW"].fillna("").astype(str))

In [79]:
y=ultimate['Sentiment']

In [80]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.8,      
    test_size=0.2,       
    random_state=42,     
    shuffle=True,        
    stratify=y) 

In [81]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [82]:
clf = MultinomialNB()


clf.fit(X_train, y_train)


y_pred = clf.predict(X_test)

In [83]:
acc = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {acc:.4f}")


Test Accuracy: 0.7500


In [84]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

    negative       0.86      0.60      0.71        10
    positive       0.69      0.90      0.78        10

    accuracy                           0.75        20
   macro avg       0.77      0.75      0.74        20
weighted avg       0.77      0.75      0.74        20



In [95]:
def predict_sentiment(review: str, model, vectorizer) -> str:
    review_list = [review]
    
    

    
    X_vect = vectorizer.transform(review_list)

    
    pred = model.predict(X_vect)

    
    return pred[0]

In [103]:

example = "the product is good"
print("Predicted sentiment:", predict_sentiment(example, clf, vectorizer))

Predicted sentiment: positive


# 5

In [104]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [107]:
vectorizer1 = TfidfVectorizer(max_features=300, stop_words="english",lowercase=True)

In [108]:
X = vectorizer1.fit_transform(ultimate["REVIEW"].fillna("").astype(str))

In [109]:
y=ultimate['Sentiment']

In [110]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.75,      
    test_size=0.25,       
    random_state=42,     
    shuffle=True,        
    stratify=y)

In [111]:
from sklearn.ensemble import RandomForestRegressor


In [117]:
# Example: Convert to binary numeric values
y_train = y_train.replace({'positive': 1, 'negative': 0})
y_test = y_test.replace({'positive': 1, 'negative': 0})


In [118]:
clf1 = RandomForestRegressor()


clf1.fit(X_train, y_train)


y_pred = clf1.predict(X_test)

In [120]:
from sklearn.metrics import precision_score, recall_score, f1_score

y_pred = [1 if p >= 0.5 else 0 for p in y_pred]


precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Precision: 0.6470588235294118
Recall: 0.9166666666666666
F1 Score: 0.7586206896551724


In [124]:
def vectorize_text(text, vectorizer):
    if isinstance(text, str):
        text = [text]  # convert single string to list
    
    return vectorizer.transform(text).toarray()

In [128]:
text1='the product is  beautiful '
vectorize_text(text1,vectorizer1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 